### ISSUE TITLE
Google Tag Manager Support

### ISSUE THREAD

**Issue by cmackay** [cmackay/google-analytics-plugin#31]
This ticket is for tracking the work for exposing tag manager api features

**Comment by jonystorm** [comment]
Hi @cmackay I was looking for a plugin that allows me to use GTM on my cordova app, does this plugin support it yet? In that case, how can I use it for it? Does it support GTM V2?

Thanks

-Jonatan

**Comment by cmackay** [comment]
Hi Jonatan,

There was work started to integrate with the google tag manager in the branch (feature/gtm). I haven't looked at it in a long time and I was going to close this ticket since I haven't dedicated time to it recently. I would welcome any contribution if you wanted to help out on it. I forget what the state of the branch is. I guess part of the reason I have not dedicated much time towards the integration is that I haven't had a direct need for the tag manager and I haven't heard many requests for having it integrated. But since you are also mentioning it, I may try to take another look at it and see what needs to be finished up. But feel free to provide any ideas you have for specific features you are looking for.

Thanks,

-Craig

**Comment by jonystorm** [comment]
I've been looking for a plugin that allows me track events using GTM V2 on Android and iOS. I haven't found one that works properly yet, and I found yours but didn't know in which state it was.
I need to be able to track and dispatch events on demand, as with any GA, but through GTM.

Thanks,

-Jonatan

**Comment by zmagyar** [comment]
Actually I'm working on this again as now came the time when we really need this. The iOS version on the current branch is not working due to some recent SDK function rename. I have fixed that in my fork and added a few more improvements. 

There are a few more fixes I'm considering and once those are passed I will make a pull request here.

**Comment by cmackay** [comment]
Hi Zoltan,

Thats great. I appreciate your help with this. Once you have a pull request, I will review the Android work I had done and see what updates are needed for that.

Thanks!

-Craig

**Comment by cmackay** [comment]
I don't think this is going to happen anytime soon. Maybe if in the future I have time or a need for this, I will look into it more. Its not only the time required in implementing this feature but also the time it takes to provide ongoing support of it. I welcome pull request if others want to add this. The pull requests will have to be consistent with the current code and ready for use by users. Also it appears there is no direct dependency between the tag manager and analytics library so this code could be a completely separate plugin. If you want to take what is in the branch and clean it up and get it to a separate project that might be a good option. I might look into this more at a later date but until then I am marking this wontfix.
