### ISSUE TITLE
Get tracker object.

### ISSUE THREAD

**Issue by nvdcmptr** [cmackay/google-analytics-plugin#33]
How can i  get tracker object in non GAITrackedViewController?
I want use "sendException: withNSException:" method.

I try 
```Objective-c
id tracker=[GAI sharedInstance].defaultTracker;
```
but not useful.

**Comment by cmackay** [comment]
Are you asking how to use the native api? Here is the site for the iOS native sdk docs.

https://developers.google.com/analytics/devguides/collection/ios/v3/
https://developers.google.com/analytics/help/
