### ISSUE TITLE
use strict not working well with cordova?

### ISSUE THREAD

**Issue by boynet** [cmackay/google-analytics-plugin#35]
for example if I send number into sendEvent label than it throws(we should call .toString but that for another issue)
````
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
````
inside cordova checkArgs function

**Comment by cmackay** [comment]
Thanks for your message. You might want to submit this issue to the Cordova repository containing checkArgs. Also if  you have a proposed solution for handling this within the plugin, you are welcome to submit a pull request for review.

Thanks,

-Craig

**Comment by boynet** [comment]
why not to remove use strict from the production code? only use it on dev

**Comment by cmackay** [comment]
I will remove 'use strict' and push out a new release

**Comment by cmackay** [comment]
A new version of the plugin has been published to the cordova repository with the change.

http://plugins.cordova.io/#/package/com.cmackay.plugins.googleanalytics

**Comment by boynet** [comment]
thanks :+1:
