### ISSUE TITLE
Google Analytics cannot be resolved

### ISSUE THREAD

**Issue by pacotole** [cmackay/google-analytics-plugin#37]
In Android when I test in debug mode the plugin works fine.
But if I build in release mode and open it with eclipse return a lot of "Google Analytics cannot be resolved" errors. Is necessary to do something more in Eclipse?

Finally I can build and sign for release following this (method 2): http://ilee.co.uk/Sign-Releases-with-Cordova-Android/

**Comment by cmackay** [comment]
I don't really use eclipse so I am not sure how it works with Cordova plugins and their dependencies. You might want to see if there is a cordova plugin for eclipse. If there is anything that can easily be done to this plugin to better support working in eclipse, let me know. Sorry I can't be more help.

Thanks,

-Craig
