### ISSUE TITLE
Integration with Adobe PhoneGap build

### ISSUE THREAD

**Issue by jeresiv** [cmackay/google-analytics-plugin#40]
Can this plugin be available through Phonegap build: https://build.phonegap.com/

**Comment by cmackay** [comment]
The plugin is in the cordova repository but it looks like the phonegap repository requires a paid subscription to upload plugins. :( Seems odd. https://build.phonegap.com/plans If you have an account and want to upload it you are welcome to. 

Thanks!

-Craig

**Comment by cmackay** [comment]
Also, I sent an email to Adobe that they should review their policy when it come to open source projects submitting plugins. I will let you know if I hear back from them.

**Comment by jeresiv** [comment]
Thanks Craig!

I have a paid subscription but when I attempt to add your plugin is says that a plugin with your name already exists. My guess is someone has uploaded your plugin privately. I will also contact Adobe to see what they can do.

**Comment by zigzag-way** [comment]
Hi guys! How can we go ahead with this issue? May be we can find someone from Adobe-PhoneGap team?

**Comment by cmackay** [comment]
Hi @zigzag-way! Yeah if you want to try submitting it to the repository, give it a try or feel free to follow up with Adobe. I sent an email to Adobe a month ago but I have not received a response.

Thanks,

-Craig

**Comment by cmackay** [comment]
Thanks @zigzag-way for the additional info on regarding plugin submission that you posted in a different issue #41. I wonder if that works for unpaid subscribers as well. The main thing I have been referring to regarding plugin submission is the https://build.phonegap.com/plugins page where it says "Please upgrade your PhoneGap Build account to submit a plugin." and the page https://build.phonegap.com/ in the plan section where it says upload plugins NO. But it does say that it supports plugins from third party plugins like the Cordova repository where this is already registered. How come you cant use this plugin from the Cordova repository? Does that work for you?

**Comment by cmackay** [comment]
@zigzag-way I was reading through the page you sent in more detail and it says that plugins.cordova.io is deprecated. I wasn't aware of that. I will try to look into this more over the next few days so hopefully I can get this resolved soon by either publishing to phonegap or npm. Thanks!

**Comment by jeresiv** [comment]
I've gotten a paid account, but when I try to add the plugin it says that it already exists. But its not in the searchable list of plugins, this leads me to believe that someone has added your plugin as a private plugin and that is blocking me from adding it. I have contacted Adobe but they have yet to respond.

**Comment by jeresiv** [comment]
So I got a response from the PhoneGap team and apparently if you add the plugin on npm it will be accessible through PhoneGap build.

**Comment by cmackay** [comment]
Thanks @jeresiv! I will add it hopefully later on today.

**Comment by cmackay** [comment]
I added the plugin to npm using the instructions from:

**Comment by cmackay** [comment]
Also when testing it out with the phonegap build, be sure to include the source attribute:

<gap:plugin name="com.cmackay.plugins.googleanalytics" source="npm" />

**Comment by zigzag-way** [comment]
Yahoo!!! It is working now!!! Thx a log Craig!

**Comment by zigzag-way** [comment]
Btw guys, has anyone seen the cordova\phonegap plugin to find the list of installed\running app on ios?

**Comment by cmackay** [comment]
@zigzag-way Glad everything is working. :)

I am not familiar with a plugin for listing apps. I would think there might be one but I haven't used one.

**Comment by jeresiv** [comment]
Yep thanks a lot Craig, love the plugin =)

**Comment by cmackay** [comment]
Thanks @jeresiv :)
