### ISSUE TITLE
Great Job on the Google Analytics Plugin

### ISSUE THREAD

**Issue by writeosahon** [cmackay/google-analytics-plugin#41]
@cmackay Great job on the plugin. It's easy to use and it's various functions provide adequate flexibility.

Thanks for this. I wish I could "star" it twice!! :)
Please keep the updates coming, especially when new updates of the Google Analytics SDK become available.

Cheers

**Comment by cmackay** [comment]
Thanks! @writeosahon :)

I appreciate the feedback. If you ever notice new SDK updates that are not yet integrated with the plugin or have ideas for new features/improvements, please let me know.

Thanks!

-Craig

**Comment by zigzag-way** [comment]
http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#Plugins - according to this docs you can submit plugin here - www.npmjs.com - and all users will be able to use it. May be I misunderstand smth...

**Comment by zigzag-way** [comment]
As I can see here (http://community.phonegap.com/nitobi/searches?query=submit+plugin&x=0&y=0&style=topics) this is a usual case for manual submitting...
