### ISSUE TITLE
Google Play Campaign Attribution

### ISSUE THREAD

**Issue by cauboy** [cmackay/google-analytics-plugin#42]
According to the [docs](https://developers.google.com/analytics/devguides/collection/android/v4/campaigns), some lines must to be added to the AndroidManifest for Google Play Campaign Attribution.

Are there any reasons why those are not added?

See: https://developers.google.com/analytics/devguides/collection/android/v4/campaigns
And an implementation here: https://github.com/appfeel/analytics-google/blob/master/plugin.xml#L31

Excerpt:
>1. Add the Google Analytics receiver to your AndroidManifest.xml file. To add the Google Analytics receiver to the manifest, copy and paste the following markup:
```
<!-- Used for Google Play Store Campaign Measurement-->
<service android:name="com.google.android.gms.analytics.CampaignTrackingService" />
<receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
          android:exported="true">
  <intent-filter>
    <action android:name="com.android.vending.INSTALL_REFERRER" />
  </intent-filter>
</receiver>
```

**Comment by cmackay** [comment]
You only add entries for the features you need. I have not used Google Play Campaign Attribution but if you want to use that give it a try. It should work.
