### ISSUE TITLE
iOS Xcode 7 runtime error

### ISSUE THREAD

**Issue by dbroadhurst** [cmackay/google-analytics-plugin#47]
I've run into an  issue when building with Xcode 7. My App builds but I'm getting the following error in the output window.

[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON = ["INVALID","GoogleAnalytics","setIDFAEnabled",[]]

**Comment by cmackay** [comment]
IDFA is not supported in this plugin for iOS due to causing many app store submission issues. Refer to the prior issues for more information.
https://github.com/cmackay/google-analytics-plugin/search?q=idfa&type=Issues&utf8=%E2%9C%93  Thanks!

**Comment by cmackay** [comment]
Also if you are not calling enableAdvertisingIdCollection and receiving this issue during building then this issue is probably related to whatever is causing the other issue you submitted #48 which I will be looking into.

Thanks!
