### ISSUE TITLE
"AnalyticsReceiver is not registered or is disabled" error when using plugin

### ISSUE THREAD

**Issue by avaz-19** [cmackay/google-analytics-plugin#52]
Hi,

I'm trying to use the google analytics plugin.  I've created an analytics account on Google and I've added your plugin correctly to my cordova project.  The README does not have any documentation on how to setup the native side of the plugin.  I'm getting a "AnalyticsReceiver is not registered or is disabled" error when trying to use the plugin.  The google documentation says to add a few lines to the gradle build script and add a downloaded json file to your project.  Any help will be greatly appreciated.

**Comment by avaz-19** [comment]
My apologies.  I just wasn't setup on the Google developers site.  Everything is working now.  Thanks!

**Comment by cmackay** [comment]
No problem :) glad you resolved the issue

**Comment by avaz-19** [comment]
This is what I'm seeing in the logging when using the plugin:

I/GAv4﹕ Google Analytics 8.1.15 is starting up. To enable debug logging on a device run:
    adb shell setprop log.tag.GAv4 DEBUG
    adb logcat -s GAv4
 W/GAv4﹕ AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
W/GAv4﹕ CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
W/GAv4﹕ AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.

Is there some part of the setup that I've missed?

**Comment by cmackay** [comment]
A new release has been published to address those warnings. you will have to update your project for the changes to take effect.

**Comment by avaz-19** [comment]
Thanks!  That resolved my issue.  Appreciate the quick response :+1:

**Comment by cmackay** [comment]
Great, glad it resolved the issue. :) Thanks for reporting it!
