### ISSUE TITLE
Phonegap Build

### ISSUE THREAD

**Issue by vespino** [cmackay/google-analytics-plugin#58]
Any chance of this plugin working with Phonegap Build?

**Comment by cmackay** [comment]
Do you get an error message? Did you have any details?

**Comment by vespino** [comment]
Are you saying the plugin should work with PGB? I didn't look into any errors, but my app seemed to stop due to a JavaScript error.

**Comment by cmackay** [comment]
It was working with phone gap and I am not aware of any issues. Let me know if you have any error details.

**Comment by cmackay** [comment]
Here is an older issue related to phonegap so you can see how others have integrated the plugin with their phonegap build. https://github.com/cmackay/google-analytics-plugin/issues/40

**Comment by cmackay** [comment]
you may need the source attribute when including the plugin:

**Comment by vespino** [comment]
I have tested another plugin which works fine.
