### ISSUE TITLE
ERROR: Method 'setIDFAEnabled:' not defined in Plugin 'GoogleAnalytics'

### ISSUE THREAD

**Issue by hassankhan** [cmackay/google-analytics-plugin#59]
Hi, I'd like to enable IDFA in Google Analytics. I used the `enableAdvertisingIdCollection()` but I get the error mentioned in the title. Is this unsupported now?

**Comment by cmackay** [comment]
That feature is not supported. It was at one point but due to issues it was removed. There are multiple closed issues related to this.
