### ISSUE TITLE
Install via npm

### ISSUE THREAD

**Issue by Jacse** [cmackay/google-analytics-plugin#61]
Would be cool if we could be able to install like so: 
`cordova plugin add cordova-plugin-google-analytics`

That's the way most cordova plugins are installed as of Cordova 5.0+

**Comment by cmackay** [comment]
I use cordova plugin add to install it. what is the issue?

cordova plugin add com.cmackay.plugins.googleanalytics

**Comment by Jacse** [comment]
Sorry for being unclear - it's more a naming-convention thing as most plugins follow the above format.

Not an issue at all, merely suggesting to follow the new naming-convention :+1:

**Comment by cmackay** [comment]
looks like https://www.npmjs.com/package/cordova-plugin-google-analytics is taken :)
