### ISSUE TITLE
Sound play issue while enable google-analytics object

### ISSUE THREAD

**Issue by sathiyaraj45** [cmackay/google-analytics-plugin#65]
Hi,
I installed google analyics plugin my cordova 5.1.1 project. While i declare the following code mean 

        var analytics = navigator.analytics;
	 console.log(analytics);
	 analytics.setTrackingId('UA-xxxxxx-y');
	 analytics.sendAppView('landing_page', successCallback, errorCallback);

i got error Object {code: 0}  in cordova media play

**Comment by cmackay** [comment]
I don't know what that means.  I would recommend checking the native sdks support groups. This plugin provides a thin wrapper around the native sdks so you are more likely to find better information on the Google Analytics native plugins within there. Feel free to reopen this if you get more info and think it is a plugin related issue. Here is the analytics developers site. https://developers.google.com/analytics/
