### ISSUE TITLE
Application carshes on Android

### ISSUE THREAD

**Issue by RezaRahmati** [cmackay/google-analytics-plugin#66]
Hi

When I try to use the plugin it compiles fine but when I run the app on device it crashes.
Do you have any clue?

Android 5.1.1
Cordova 5.4.1
![4](https://cloud.githubusercontent.com/assets/10086092/15454685/f869c11c-200d-11e6-82bd-47c1244f7d91.png)

**Comment by cmackay** [comment]
I don't have a clue as to why your application is crashing. Maybe if you get an error message you can submit that. I would recommend creating a new application adding the plugin and then if it fails enable logging and see what the error message is.
