### ISSUE TITLE
How to get logs of all events?

### ISSUE THREAD

**Issue by pallaviMN** [cmackay/google-analytics-plugin#68]
I would like to display log of all tracked events & tracked views. How can i get that?

**Comment by cmackay** [comment]
This plugin provides a wrapper around the native analytics sdks which focuses on data collection. Viewing of the events and views is primarily done through the reporting interface for google analytics. https://www.google.com/analytics/

Also this information is available through the APIs for reporting. For more details on this refer to:
https://developers.google.com/analytics/

**Comment by pallaviMN** [comment]
@cmackay , i went through the google analytics, can you please tell which API can be used to get the  details of viewing events & screens

**Comment by cmackay** [comment]
I don't know which api you use for retrieving events. It is not something supported for this plugin. I would refer to the docs or there is a getting help link at the bottom of the docs page. Also if you search around you can see others are doing it so it should be possible. Maybe this will help. It looks relevant. http://stackoverflow.com/questions/8371533/how-to-read-events-from-google-analytics-api  If you have further questions on google analytics reporting apis, I would search on google and read the docs. Then maybe if that doesn't work contact their help. Good luck with it!
