### ISSUE TITLE
Intel XDK does not recognise plugin

### ISSUE THREAD

**Issue by rakeshtembhurne** [cmackay/google-analytics-plugin#69]
I am trying to do iOS development but the Intel XDK seems to be not recognizing the plugin. I think it has to do something with newer version of Intel XDK (3522). Earlier we were able to check plugin is loaded with `navigator.analytics` is null or not. In debug mode when I press 'navigator' I see many keys but not analytics.

OS: Ubuntu16.04
Intel XDK: v3522
Device: iPhone 5S (version 9.3.5)

**Comment by cmackay** [comment]
This may be related to the other intel XDK issues marked as "wont fix". https://github.com/cmackay/google-analytics-plugin/issues/62

If you find a fix that requires a code change, then feel free to submit a PR. This plugin is designed to work as a standard cordova plugin and works with the cordova cli. I don't use XDK and I don't know what it does differently that causes plugin issues. If there is any additional information regarding XDK issues, feel free to post to issue #62. Thanks!
