### ISSUE TITLE
AllowIDFACollection callback never called in iOS

### ISSUE THREAD

**Issue by S-unya** [cmackay/google-analytics-plugin#70]
Testing this on Android and iOS, I call:
`analytics.enableAdvertisingIdCollection(() => {
            alert('enableAdvertisingIdCollection success');// eslint-disable-line no-console
        }, () => {
            alert('enableAdvertisingIdCollection failure');// eslint-disable-line no-console
        });`
Android calls the success function reliably, but iOS never does.

Checking on the GoogleAnalytics dashboard, I see that Android is logging events but iOS is still considered to be off and they are suggesting setting `allowIDFACollecttion=YES`on appropriate views.

This suggests that this is never set in the iOS implementation

**Comment by cmackay** [comment]
It is not set in the implementation on iOS due to multiple issues related to IDFA and iOS. For more info refer to #60 and there are other closed IDFA related issues. If you want this behavior I would recommend forking and applying it to your branch.

**Comment by cmackay** [comment]
https://github.com/cmackay/google-analytics-plugin/search?q=idfa&type=Issues&utf8=%E2%9C%93

**Comment by S-unya** [comment]
Understood. Thanks.
