### ISSUE TITLE
Build error [UNEXPECTED TOP-LEVEL EXCEPTION]

### ISSUE THREAD

**Issue by sandroweb** [cmackay/google-analytics-plugin#71]
When I run the command `$ cordova run android --verbose`

![image](https://cloud.githubusercontent.com/assets/260201/20009187/a7223e56-a28a-11e6-957a-c76964430c6b.png)

After remove your plugin, my app compile without errors.

I'm tested with Cordova Android Engine 5.0.0 and 5.1.1.
My Cordova version is 6.3.1.
The minSDKVersion of my App is 15.

**Comment by cmackay** [comment]
I believe that means multiple plugins are conflicting. What other plugins are you using?

I see an issue on stackoverflow that might provide some possible work arounds:

http://stackoverflow.com/questions/32511242/cordova-error-on-build-only-for-android-com-android-dex-dexexception-multiple

**Comment by sandroweb** [comment]
I see this issue, but I need a solution to configure on config.xml, to generate the project without problems.

And I use a lot other plugins, but I need maintain these plugins.

![image](https://cloud.githubusercontent.com/assets/260201/20011250/1419d788-a292-11e6-8cea-7ee71816e032.png)

You know any solution to configure the "[solution](http://stackoverflow.com/questions/32511242/cordova-error-on-build-only-for-android-com-android-dex-dexexception-multiple)" into config.xml?

**Comment by cmackay** [comment]
Hmm, not sure. Sorry. We can keep the issue open and maybe others might have recommendations. Thanks for the information.

**Comment by petarov** [comment]
Just a thought. Perhaps you should first identify which plugins are conflicting. Go to your project's `plugins` folder and run something like:

    $ grep com.google.android.gms **/*.xml -R

Afterwards, you can check if there are any updates for the plugins that use, what seems, older gms dependencies.

**Comment by sandroweb** [comment]
Thank you @petarov and @cmackay for collaboration!!! Now the Android are building the app normaly.
