### ISSUE TITLE
cordova platform add fails

### ISSUE THREAD

**Issue by william-rosa** [cmackay/google-analytics-plugin#78]
I'm seeing an issue when using this plugin with other plugins that utilise googleservices.

During 'cordova platform add', when it tries to install a plugin that uses googleservices after it has already added one before, cordova fails.

I tracked the issue down to the project.properties file in this plugin. The problematic line is this:
cordova.system.library.1=com.google.android.gms:play-services-analytics:+

It seems like using the '+' version breaks things, if I remove that and add a specific version, everything works well.

My problem is that our deployment process starts from scratch each time it deploys, re-adding the platforms before I have a chanse to manually change the '+' to a specific version.

Based on Cordova's best practices, using '+' for version is strongly discouraged.

**Comment by cmackay** [comment]
same issue as #77
